site_name: Snowfakery documentation
site_url: ""
theme: readthedocs
theme_dir: custom_theme
repo_url: https://github.com/SFDO-Tooling/Snowfakery/
nav:
  - index.md
  - salesforce.md
  - Fake Data: fakedata.md
  - embedding.md
  - extending.md
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 4
plugins:
  - search
  - snowfakery_fakes:
      build_locales: True # do or do not generate locales
      # should be True on the fake-data-docs branch
