common_fakes:
  - company
  - name
  - name_female
  - name_male
  - last_name
  - first_name
  - first_name_female
  - first_name_male
  - first_name_nonbinary
  - catch_phrase
  - year
  - email
  - phone_number
  - building_number
  - city
  - state
  - postalcode
  - administrative_unit
  - street_address
  - country
  - country_code
  - current_country
  - current_country_code
  - time
  - paragraph
  - word
  - sentence
  - text
