name: CI

on: [push]

env:
  COVERALLS_PARALLEL: true
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -VV
          python -m pip install --upgrade pip pip-tools
          make dev-install

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox

      - name: Report Coverage
        run: coveralls

      - name: Test snowbench
        run: |
          python setup.py install
          snowbench examples/basic-salesforce.recipe.yml 10_000 Account --number-of-processes 4

  with_cci:
    name: With CumulusCI
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip pip-tools
          make dev-install
          python -m pip install cumulusci

      - name: Run Tests
        run: python -m pytest

  windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          python -VV
          python -m pip install --upgrade pip pip-tools
          make dev-install

      - name: Run Tests
        run: python -m pytest

  coveralls_done:
    name: Finalize coveralls
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$GITHUB_SHA&payload[status]=done"
